In [34]:
pip install pandas scikit-learn seaborn matplotlib numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.3)
Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: matplotlib in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.11.1)
Requirement already satisfied: numpy in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: six>=1.5 in C:\Users\arthu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 1.1 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.2 MB 1.1 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/8.2 MB 1.1 MB/s eta 0:00:08
   ----- ---------------------------------- 1.0/8.2 MB 908.5 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.2 MB 1.1 MB/s eta 0:00:07
   ---------- ----------------------------- 2.1/8.2 MB 1.3 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.2 MB 1.4 MB/s eta 0:00:05
   -------------- ------------------------- 2.9/8.2 MB 1.4 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.2 MB 1.4 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.2 MB 1.4 MB/s eta 0:00:04
   ------------------- -------------------- 3.9/8.2 MB 1.5 MB/s eta 0:00:03
   --------------------- ------------------ 4.5/8.2 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.2 MB 1.6 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.2 MB 1.7 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.2 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.2 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.9 MB/s eta 0:00:01
   ------------------------------------ --- 7.6/8.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 1.9 MB/s  0:00:04
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.8/36.6 MB 2.5 MB/s eta 0:00:15
   - -------------------------------------- 1.3/36.6 MB 2.5 MB/s eta 0:00:15
   -- ------------------------------------- 1.8/36.6 MB 2.4 MB/s eta 0:00:15
   -- ------------------------------------- 2.4/36.6 MB 2.3 MB/s eta 0:00:15
   --- ------------------------------------ 2.9/36.6 MB 2.4 MB/s eta 0:00:15
   --- ------------------------------------ 3.4/36.6 MB 2.4 MB/s eta 0:00:14
   ---- ----------------------------------- 3.9/36.6 MB 2.4 MB/s eta 0:00:14
   ---- ----------------------------------- 4.5/36.6 MB 2.4 MB/s eta 0:00:14
   ----- ---------------------------------- 5.0/36.6 MB 2.4 MB/s eta 0:00:14
   ----- ---------------------------------- 5.2/36.6 MB 2.3 MB/s eta 0:00:14
   ----- ---------------------------------- 5.2/36.6 MB 2.3 MB/s eta 0:00:14
   ----- ---------------------------------- 5.2/36.6 MB 2.3 MB/s eta 0:00:14
   ------ --------------------------------- 5.5/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.0/36.6 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.6/36.6 MB 2.0 MB/s eta 0:00:16
   ------- -------------------------------- 7.1/36.6 MB 2.0 MB/s eta 0:00:15
   -------- ------------------------------- 7.6/36.6 MB 2.0 MB/s eta 0:00:15
   -------- ------------------------------- 8.1/36.6 MB 2.1 MB/s eta 0:00:14
   --------- ------------------------------ 8.7/36.6 MB 2.1 MB/s eta 0:00:14
   --------- ------------------------------ 8.7/36.6 MB 2.1 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ---------- ----------------------------- 9.2/36.6 MB 2.0 MB/s eta 0:00:14
   ----------- ---------------------------- 10.5/36.6 MB 1.6 MB/s eta 0:00:17
   ------------ --------------------------- 11.0/36.6 MB 1.6 MB/s eta 0:00:16
   ------------ --------------------------- 11.5/36.6 MB 1.6 MB/s eta 0:00:16
   ------------- -------------------------- 12.1/36.6 MB 1.7 MB/s eta 0:00:15
   ------------- -------------------------- 12.6/36.6 MB 1.7 MB/s eta 0:00:15
   -------------- ------------------------- 13.1/36.6 MB 1.7 MB/s eta 0:00:14
   -------------- ------------------------- 13.6/36.6 MB 1.8 MB/s eta 0:00:14
   --------------- ------------------------ 14.2/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 14.7/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 14.9/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 15.2/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 15.5/36.6 MB 1.7 MB/s eta 0:00:13
   ----------------- ---------------------- 16.0/36.6 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 16.5/36.6 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 17.0/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.6/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.1/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.6/36.6 MB 1.8 MB/s eta 0:00:10
   -------------------- ------------------- 19.1/36.6 MB 1.9 MB/s eta 0:00:10
   --------------------- ------------------ 19.7/36.6 MB 1.9 MB/s eta 0:00:10
   ---------------------- ----------------- 20.2/36.6 MB 1.9 MB/s eta 0:00:09
   ---------------------- ----------------- 20.7/36.6 MB 1.9 MB/s eta 0:00:09
   ----------------------- ---------------- 21.2/36.6 MB 1.9 MB/s eta 0:00:09
   ----------------------- ---------------- 21.8/36.6 MB 1.9 MB/s eta 0:00:08
   ------------------------ --------------- 22.3/36.6 MB 1.9 MB/s eta 0:00:08
   ------------------------ --------------- 22.8/36.6 MB 1.9 MB/s eta 0:00:08
   ------------------------- -------------- 23.3/36.6 MB 2.0 MB/s eta 0:00:07
   -------------------------- ------------- 23.9/36.6 MB 2.0 MB/s eta 0:00:07
   -------------------------- ------------- 24.4/36.6 MB 2.0 MB/s eta 0:00:07
   --------------------------- ------------ 24.9/36.6 MB 2.0 MB/s eta 0:00:06
   ---------------------------- ----------- 25.7/36.6 MB 2.0 MB/s eta 0:00:06
   ---------------------------- ----------- 26.2/36.6 MB 2.0 MB/s eta 0:00:06
   ----------------------------- ---------- 26.7/36.6 MB 2.0 MB/s eta 0:00:05
   ----------------------------- ---------- 27.3/36.6 MB 2.0 MB/s eta 0:00:05
   ------------------------------ --------- 27.8/36.6 MB 2.0 MB/s eta 0:00:05
   ------------------------------ --------- 28.3/36.6 MB 2.0 MB/s eta 0:00:05
   ------------------------------- -------- 28.6/36.6 MB 2.0 MB/s eta 0:00:04
   ------------------------------- -------- 28.8/36.6 MB 2.0 MB/s eta 0:00:04
   ------------------------------- -------- 29.1/36.6 MB 2.0 MB/s eta 0:00:04
   ------------------------------- -------- 29.1/36.6 MB 2.0 MB/s eta 0:00:04
   -------------------------------- ------- 30.1/36.6 MB 2.0 MB/s eta 0:00:04
   --------------------------------- ------ 30.9/36.6 MB 2.0 MB/s eta 0:00:03
   ---------------------------------- ----- 31.2/36.6 MB 2.0 MB/s eta 0:00:03
   ---------------------------------- ----- 32.0/36.6 MB 2.0 MB/s eta 0:00:03
   ----------------------------------- ---- 32.2/36.6 MB 2.0 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/36.6 MB 2.0 MB/s eta 0:00:02
   ------------------------------------ --- 33.3/36.6 MB 2.1 MB/s eta 0:00:02
   ------------------------------------ --- 33.8/36.6 MB 2.1 MB/s eta 0:00:02
   ------------------------------------- -- 34.3/36.6 MB 2.1 MB/s eta 0:00:02
   -------------------------------------- - 34.9/36.6 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.6 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 2.1 MB/s  0:00:17
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, seaborn, scikit-learn

   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------- ----------------- 4/7 [joblib]
   ---------------------------- ----------- 5/7 [seaborn]
   ---------------------------- ----------- 5/7 [seaborn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------------- 7/7 [scikit-learn]

Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.1 scipy-1.18.1 seaborn-0.13.2 threadpoolctl-3.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\arthu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# 1. a)

In [106]:
import pandas as pd

df = pd.read_csv('houses_to_rent.csv')

display(df)

,Unnamed: 0,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa,rent amount,property tax,fire insurance,total
0,0,1,240,3,3,4,-,acept,furnished,R$0,"R$8,000","R$1,000",R$121,"R$9,121"
1,1,0,64,2,1,1,10,acept,not furnished,R$540,R$820,R$122,R$11,"R$1,493"
2,2,1,443,5,5,4,3,acept,furnished,"R$4,172","R$7,000","R$1,417",R$89,"R$12,680"
3,3,1,73,2,2,1,12,acept,not furnished,R$700,"R$1,250",R$150,R$16,"R$2,116"
4,4,1,19,1,1,0,-,not acept,not furnished,R$0,"R$1,200",R$41,R$16,"R$1,257"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,6075,1,50,2,1,1,2,acept,not furnished,R$420,"R$1,150",R$0,R$15,"R$1,585"
6076,6076,1,84,2,2,1,16,not acept,furnished,R$768,"R$2,900",R$63,R$37,"R$3,768"
6077,6077,0,48,1,1,0,13,acept,not furnished,R$250,R$950,R$42,R$13,"R$1,255"
6078,6078,1,160,3,2,2,-,not acept,not furnished,R$0,"R$3,500",R$250,R$53,"R$3,803"
6079,6079,1,60,2,1,1,4,acept,furnished,R$489,"R$1,900",R$0,R$25,"R$2,414"

# 1. b)

In [107]:
df.head()

,Unnamed: 0,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa,rent amount,property tax,fire insurance,total
0,0,1,240,3,3,4,-,acept,furnished,R$0,"R$8,000","R$1,000",R$121,"R$9,121"
1,1,0,64,2,1,1,10,acept,not furnished,R$540,R$820,R$122,R$11,"R$1,493"
2,2,1,443,5,5,4,3,acept,furnished,"R$4,172","R$7,000","R$1,417",R$89,"R$12,680"
3,3,1,73,2,2,1,12,acept,not furnished,R$700,"R$1,250",R$150,R$16,"R$2,116"
4,4,1,19,1,1,0,-,not acept,not furnished,R$0,"R$1,200",R$41,R$16,"R$1,257"

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6080 entries, 0 to 6079
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      6080 non-null   int64
 1   city            6080 non-null   int64
 2   area            6080 non-null   int64
 3   rooms           6080 non-null   int64
 4   bathroom        6080 non-null   int64
 5   parking spaces  6080 non-null   int64
 6   floor           6080 non-null   str
 7   animal          6080 non-null   str
 8   furniture       6080 non-null   str
 9   hoa             6080 non-null   str
 10  rent amount     6080 non-null   str
 11  property tax    6080 non-null   str
 12  fire insurance  6080 non-null   str
 13  total           6080 non-null   str
dtypes: int64(6), str(8)
memory usage: 665.1 KB

In [109]:
df.isnull().sum()

Unnamed: 0        0
city              0
area              0
rooms             0
bathroom          0
parking spaces    0
floor             0
animal            0
furniture         0
hoa               0
rent amount       0
property tax      0
fire insurance    0
total             0
dtype: int64

É estranho o fato de que não existe nenhum null presente na tabela. Além disso, colunas como hoa e rent amount deveriam ser float, não str

# 2. a)

In [110]:
colunas = ['hoa', 'rent amount', 'property tax', 'fire insurance', 'total']

for coluna in colunas:
    df[coluna] = (
        df[coluna]
        .astype(str)
        .str.replace('R\$', '', regex=True)
        .str.replace('.', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('Sem info', '0', regex=False)
        .str.replace('Incluso', '0', regex=False)
        .str.strip()
    )
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce').fillna(0)

display(df[colunas].head())

<>:7: SyntaxWarning: invalid escape sequence '\$'
<>:7: SyntaxWarning: invalid escape sequence '\$'
C:\Users\arthu\AppData\Local\Temp\ipykernel_23192\1085973066.py:7: SyntaxWarning: invalid escape sequence '\$'
  .str.replace('R\$', '', regex=True)

    hoa  rent amount  property tax  fire insurance  total
0     0         8000          1000             121   9121
1   540          820           122              11   1493
2  4172         7000          1417              89  12680
3   700         1250           150              16   2116
4     0         1200            41              16   1257

# 2. b)

In [111]:
df['floor'] = df['floor'].replace('-', '0')
df['floor'] = pd.to_numeric(df['floor'], errors='coerce')
display(df['floor'].head())

0     0
1    10
2     3
3    12
4     0
Name: floor, dtype: int64

# 2. c)

In [112]:
def converter_animal(value):
    if value == 'acept':
        return 1
    elif value == 'not acept':
        return 0

df['animal'] = df['animal'].apply(converter_animal)

def converter_furniture(value):
    if value == 'furnished':
        return 1
    elif value == 'not furnished':
        return 0

df['furniture'] = df['furniture'].apply(converter_furniture)

display(df[['animal', 'furniture']].head())

   animal  furniture
0       1          1
1       1          0
2       1          1
3       1          0
4       0          0

# 3. a)

In [113]:
from sklearn.model_selection import train_test_split

X = df[['city', 'area', 'rooms', 'bathroom', 'parking spaces', 'floor', 'animal', 'furniture']]
y = df['total']

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. b)

In [114]:
from sklearn.linear_model import LinearRegression

modelo = LinearRegression()
modelo.fit(X_treino, y_treino)
previsoes = modelo.predict(X_teste)

# 3. c)

In [115]:
print(modelo.intercept_)
print(modelo.coef_)

-2282.182415200894
[ 2.00734346e+03  9.17142774e-01  3.95195323e+02  1.61777477e+03
  5.56714785e+02  1.05145517e+02 -3.47652066e+02  1.33486874e+03]

# 4. a)

In [116]:
imovel = pd.DataFrame({
    'city': [0],
    'area': [210],
    'rooms': [1],
    'bathroom': [3],
    'parking spaces': [3],
    'furniture': [1],
    'floor': [0],
    'animal': [1]
})

novo_imovel = imovel[X_treino.columns]
previsao = modelo.predict(novo_imovel)
print(previsao[0])

5816.298242312394

# 4. b)

E dificil dizer qual e a caracteristica mais impactante visto que os valores estao sendo analisados em uma variacao de 1 para y. Isso significa que esta sendo medido o impacto de, por exemplo, aumentar 1 metro quadrado de area em comparacao com aumentar 1 quarto, o que e claramente inadequado, visto que variacoes de area nao ocorreriam de 1 metro quadrado em 1 metro quadrado. Alem do mais, utilizar city desse jeito e uma caracterizacao exotica, ja que um imovel sera muito valorizado so de estar em um espaco tao valorizado quanto Sao Paulo, mas tambem existem outras cidades tao relevantes quanto que sao desconsideradas pois, em media nacional, Sao Paulo e muito melhor.